# Generated by Django 5.2.6 on 2025-12-12 15:55

import apps.bible_change.users.models.user
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=apps.bible_change.users.models.user.generate_user_id, editable=False, max_length=13, primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='비밀번호(7~13자)', max_length=13)),
                ('password2', models.CharField(blank=True, max_length=13, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('nickname', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], default='M', max_length=8)),
                ('level', models.CharField(choices=[('ADMIN', '바이블체인지 관리자'), ('MENTOR', '멘토 / 양육erial자'), ('MEMBER', '일반 멤버'), ('VISITOR', '새가족 / 방문자')], default='ADMIN', max_length=8)),
                ('membership', models.CharField(choices=[('SEEKER', '말씀 탐색자'), ('ROOTED', '말씀에 뿌리내린 자'), ('GROWING', '성장하는 자'), ('FRUITFUL', '열매 맺는 자'), ('LIGHT', '빛을 비추는 자')], default='SEEKER', max_length=10)),
                ('birth_date', models.DateField(default=apps.bible_change.users.models.user.default_birth_date)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('road_address', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_address', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('HABIT_DIFFICULTY', '말씀/독서 습관 유지 어려움'), ('LACK_OF_CONTENT', '콘텐츠 부족'), ('UX_ISSUE', '앱 사용성 불편'), ('DEVICE_ISSUE', '기기/환경 문제'), ('OTHER_APP', '다른 앱 사용'), ('DUPLICATE', '중복 계정'), ('PRIVACY', '개인 정보 삭제 요청'), ('OTHER', '기타')], help_text='탈퇴 사유', max_length=30)),
                ('detail', models.TextField(blank=True, help_text='추가 입력 사유 (선택)', null=True)),
                ('withdrawn_at', models.DateTimeField(auto_now_add=True, help_text='탈퇴 시각')),
                ('user', models.ForeignKey(blank=True, help_text='탈퇴한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
