# Generated by Django 6.0 on 2025-12-16 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_relay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible_book', models.CharField(max_length=3000, verbose_name='성경책')),
                ('chapter', models.PositiveIntegerField(verbose_name='장')),
                ('verse', models.PositiveIntegerField(verbose_name='절')),
                ('content', models.TextField(verbose_name='릴레이 댓글 내용')),
                ('is_completed', models.BooleanField(default=False, verbose_name='릴레이 완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_relay_comments', to=settings.AUTH_USER_MODEL, verbose_name='바이블 성경댓글 작성자')),
            ],
            options={
                'verbose_name': '성경릴래이댓글',
                'verbose_name_plural': '성경릴레이 댓글들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelayComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bible_relay.relay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BibleRelayComment',
        ),
    ]
